version: "3"
 
services:
  postgres:
    image: "postgres:11"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_USER: "postgres"
 
  my-rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    depends_on:
      - "postgres"
      - "my-rabbit"
    build: ./servico-produtor
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - ./servico-produtor:/produtor
      - gems:/gems

  consumer:
    depends_on:
      - "postgres"
      - "my-rabbit"
      - "producer"
    build: ./servico-consumidor
    command: bash start.sh
    ports:
      - "3001:3001"
    volumes:
      - ./servico-consumidor:/consumidor
      - consumer-gems:/gems
 
volumes:
  postgres:
  gems:
  consumer-gems:
